resolver: lts-10.3

packages:
- .

extra-deps:
- haskoin-core-0.4.2
- murmur3-1.0.3
- pbkdf-1.1.1.1
- secp256k1-0.4.8

# Because Haskoin's dependencies upper-bounds have not been updated
allow-newer: true
